version: "3"

services:

  app:
    build:
      context: ../../
      dockerfile: deploy/docker/dev.Dockerfile
    image: xino/api
    restart: always
    networks:
      - xino-api-net
    volumes:
      - ../../:/var/www/html
    env_file:
      - ../../.env
    ports:
      - "8000:80"

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - xino-api-net
    ports:
      - ":6379"

  mysql:
    image: mariadb:10.6
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=xino
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=12345
      - MYSQL_PORT=3306
    ports:
      - ":3306"
    networks:
      - xino-api-net

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  xino-api-net:
